export const Users = [
  {
    id: 1,
    profilePicture: "/assets/person/1.jpeg",
    username: "fatma mohamed",
  },
  {
    id: 2,
    profilePicture: "/assets/person/2.jpeg",
    username: "shady mohamed",
  },
  {
    id: 3,
    profilePicture: "/assets/person/3.jpeg",
    username: "shaza mohamed",
  },
  {
    id: 4,
    profilePicture: "/assets/person/4.jpeg",
    username: "mena mohamed",
  },
  {
    id: 5,
    profilePicture: "/assets/person/5.jpeg",
    username: "nana mohamed",
  },
  {
    id: 6,
    profilePicture: "/assets/person/6.jpeg",
    username: "ola mohamed",
  },
  {
    id: 7,
    profilePicture: "/assets/person/7.jpeg",
    username: "tarek mohamed",
  },
  {
    id: 8,
    profilePicture: "/assets/person/8.jpeg",
    username: "mai mohamed",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "rana mohamed",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "emy mohamed",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All ",
    photo: "assets/post/1.jpeg",
    date: "5 min ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "10 min ago",
    userId: 2,
    like: 20,
    comment: 1,
  },
  {
    id: 3,
    desc: "How are u friends",
    photo: "assets/post/3.jpeg",
    date: "30 min ago",
    userId: 3,
    like: 25,
    comment: 12,
  },
  {
    id: 4,
    desc: "what's going on",
    photo: "assets/post/4.jpeg",
    date: "35 min ago",
    userId: 4,
    like: 45,
    comment: 7,
  },
  {
    id: 5,
    desc: "Hey what's the next",
    photo: "assets/post/5.jpeg",
    date: "1 day ago",
    userId: 5,
    like: 18,
    comment: 12,
  },
  {
    id: 6,
    desc: "Tell me about your future  plan",
    photo: "assets/post/6.jpeg",
    date: "2 day ago",
    userId: 6,
    like: 23,
    comment: 2,
  },
  {
    id: 7,
    desc: "It's amazing fruits",
    photo: "assets/post/7.jpeg",
    date: "3 day ago",
    userId: 7,
    like: 17,
    comment: 18,
  },
  {
    id: 8,
    desc: "Tailand is wonderfull country",
    photo: "assets/post/8.jpeg",
    date: "50 min ago",
    userId: 8,
    like: 29,
    comment: 29,
  },
  {
    id: 9,
    desc: "Think before talk",
    photo: "assets/post/9.jpeg",
    date: "50 min ago",
    userId: 9,
    like: 29,
    comment: 6,
  },
  {
    id: 10,
    desc: "No Words To Say...!",
    photo: "assets/post/10.jpeg",
    date: "50 min ago",
    userId: 10,
    like: 29,
    comment: 26,
  },
];
